# Numerical Python

## NumPy

<a href="https://numpy.org/">
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="300px">
</a>

```python
import numpy as np
```

* Numpy provides fast numerical arrays
* Provides the `ndarray` type storing contiguous memory arrays for numeric types rather than as Python objects
* Computation with NumPy can be incredibly fast versus Python which stores numbers as individual objects
* Operators for `ndarray` implement a range of mathematical operations allowing vectorisation of computation

In [ ]:
python_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
python_array

In [1]:
import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numpy_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Stored as a contiguous block of data in memory, each item is a value and not Python objects


Arrays have properties describing their shape and contents:

In [2]:
print(numpy_array)
print(type(numpy_array))     # type of Python object
print(numpy_array.size)      # total number of values
print(numpy_array.shape)     # array shape, i.e., size of each dimension
print(numpy_array.dtype)     # data type, all stored values have this type
print(numpy_array.ndim)      # number of dimensions, ie. len(numpy_array.shape)
print(numpy_array.itemsize)  # size of each data value in bytes
print(numpy_array.nbytes)    # size of whole array in bytes, ie. numpy_array.size*numpy_array.itemsize

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
9
(3, 3)
int32
2
4
36


Every array has a dtype defining the type of values stored
* Integer values (`np.int32`, `np.uint8`, etc.)
* Float values (`np.float32`, `np.float64`)
* Boolean values (`np.bool`)
* Complex values, structure types, strings, etc.

In [3]:
values = 0, 1.5, 2
print(np.array(values))
print(np.array(values, dtype=np.uint8))
print(np.array(values, dtype=bool))

[0.  1.5 2. ]
[0 1 2]
[False  True  True]


Various functions exist for creating arrays:

$I_4$

In [ ]:
np.eye(4)

In [ ]:
np.zeros((2, 2))

In [ ]:
np.ones((2, 2))

In [ ]:
np.full((2, 2), 42)

In [ ]:
np.random.rand(2, 2)

## Questions

Be careful with the data types:

In [ ]:
array_ints = np.array((-1, 0, 1, 255))
print(array_ints.dtype)
print(array_ints)

In [ ]:
print(array_ints)
print(array_ints + 1)

In [ ]:
array_uints = array_ints.astype(np.uint8)
print(array_ints)
print(array_uints)

In [ ]:
print(array_uints)
print(array_uints + 1)

In [ ]:
np.array(-1, dtype=np.uint16)

In [ ]:
np.array(65536, dtype=np.uint16)

Be careful with floating-point arithmetic:

In [ ]:
0.1

In [ ]:
0.1 + 0.1

In [ ]:
0.1 + 0.1 + 0.1

In [ ]:
3 * np.float32(0.1)

In [ ]:
3 * np.float64(0.1)

In [ ]:
3 * np.float128(0.1)

In [ ]:
3 * np.float16(0.1)

https://0.30000000000000004.com/

Arrays can be _reshaped_:

In [ ]:
arange = np.arange(12)
print(arange.shape)
arange

In [ ]:
arange.reshape(2, 6)

In [ ]:
arange.reshape(6, 2)

In [ ]:
arange.reshape(2, 2, 3)

<img src="https://github.com/elegant-scipy/elegant-scipy/raw/master/figures/NumPy_ndarrays_v2.png" width="600px">

In [ ]:
column = arange[:, np.newaxis]
print(column.shape)
column

In [ ]:
np.newaxis is None

In [ ]:
row = column.T
print(row.shape)
row

Slicing arrays:

<img src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.svg" width="800px">

[From [software carpentry](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html)]


In [ ]:
print(numpy_array)
print(numpy_array[0, 1])
print(numpy_array[1, 0])
print(numpy_array[2, 2])

<img src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-operations-across-axes.png" width="800px">

[From [software carpentry](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html)]

In [ ]:
print(numpy_array)
print(numpy_array.mean(axis=0))
print(numpy_array.mean(axis=1))
print(numpy_array.mean())

In [ ]:
array = np.arange(60).reshape(3, 4, 5)
array

In [ ]:
array[:, :2, :].shape

In [ ]:
array[:, :2].shape

In [ ]:
array[..., :2].shape

In [ ]:
array[..., 2].shape

* When Numpy arrays are sliced, a view is returned
* This is a shallow copy of the original which uses the original allocated memory
* Changes to the view affect the original
* Deep copying can be done with the `copy` method

In [ ]:
a = np.arange(10)
print(a)

b = a[3:6]
b[:] = 0  # assign 0 to every position in b

print(a)

In [ ]:
a = np.arange(10)
print(a)

b = a.copy()[3:6]
b[:] = 0  # assign 0 to every position in b

print(a)

* Operators are overloaded on arrays to implement vectorized mathematical operations
* Eg. `__add__` (`+`) implements element-wise addition, `-` is element-wise subtraction, etc.
* Boolean operators (`==`, `<=`, etc.) are element-wise and produce arrays of boolean values

In [ ]:
a = np.random.rand(2, 2)
a

In [ ]:
mask = a > 0.5
mask

In [ ]:
a[mask]

In [ ]:
a + 10

In [ ]:
a + a

* These implement per-element operations and produce new arrays
* Matrix operators also provided:

$A \cdot A$

In [ ]:
a.dot(a)  # or a @ a, or np.dot(a, a)

$A^T$

In [ ]:
a.T  # transpose

* Assignment operators modify existing arrays rather than create new ones
* Represents another important efficiency concern, choose one method or the other depending on need

In [ ]:
print(id(a))
b = a
print(id(b))

In [ ]:
print(id(a))
print(id(b))
b = a.copy()
print(id(b))

In [ ]:
print(id(a))
print(id(b))
b += a
print(id(b))

In [ ]:
print(id(a))
print(id(b))
b = b + a
print(id(b))

## To know more

- [NumPy user guide](https://numpy.org/doc/stable/user/)

### To know _much_ more

- [NumPy Reference](https://numpy.org/doc/stable/reference/)
- [MyBinder - Elegant Scipy](https://mybinder.org/v2/gh/elegant-scipy/notebooks/master?filepath=index.ipynb) (interactive book!)

## Questions

[Some cells have been adapted from [Dr Eric Kerfoot's](https://kclpure.kcl.ac.uk/portal/eric.kerfoot.html)]